<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Guideline" nsURI="https://www.archsec.de/models/guideline/1.0"
    nsPrefix="gl">
  <eClassifiers xsi:type="ecore:EClass" name="Guideline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//Identification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FlawTarget">
    <eLiterals name="Process"/>
    <eLiterals name="Datastore" value="1"/>
    <eLiterals name="Data" value="2"/>
    <eLiterals name="InformationFlow" value="3"/>
    <eLiterals name="ExternalEntity" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//FlawTarget">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checks" upperBound="-1"
        eType="#//Check" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutomated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Check">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutomated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inspection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guideline" lowerBound="1"
        eType="#//Guideline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="findings" upperBound="-1"
        eType="#//Finding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Finding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="#//CheckState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="check" lowerBound="1" eType="#//Check"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CheckState">
    <eLiterals name="Manual"/>
    <eLiterals name="Vulnerable" value="1"/>
    <eLiterals name="Mitigated" value="2"/>
  </eClassifiers>
</ecore:EPackage>
